### ISSUE TITLE
The original Admin schema is identical to the original Guest schema

### ISSUE THREAD

**Issue by dshevtsov** [magento-devdocs/magento-openapi-transformer#6]
I previously noticed the original Admin schema is identical to the original Guest schema. My guess is that the OTP is failing to apply and since the Guest schema is returned by default.

_Originally posted by @jhadobe in https://github.com/commerce-docs/magento-openapi-transformer/pull/5#pullrequestreview-1346739787_

**Comment by dshevtsov** [comment]
I'm trying to reproduce the bug locally.

**Comment by dshevtsov** [comment]
That's what I've got:

```
-rw-r--r-- 1 dimashevtsov staff 821K Mar 21 15:48 __output__/admin-schema-redocly-2.4.6.yaml
-rw-r--r-- 1 dimashevtsov staff 165K Mar 21 15:48 __output__/customer-schema-redocly-2.4.6.yaml
-rw-r--r-- 1 dimashevtsov staff 149K Mar 21 15:48 __output__/guest-schema-redocly-2.4.6.yaml
```

**Comment by dshevtsov** [comment]
There are some concerns though:
- the README says to use a host with the protocol in the argument, and the protocol is already encoded in the script
- the username and the password for Admin are hardcoded (that might be the bug in your case, @jhadobe)

I'll change the code to eliminate these concerns.

**Comment by jhadobe** [comment]
Ah, i figured out my issue. I did not replace the default admin credentials in [the script](https://github.com/commerce-docs/magento-openapi-transformer/blob/3264d4c01ce432b5277a16cb332f2d5b04f0aee1/bin/get-rest-schemas-from-2_4#L29). we should add that to the `README.md`.

**Comment by jhadobe** [comment]
Just saw your update @dshevtsov! thanks for working on this!
